name: base
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.2.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.0
  - chardet=3.0.4
  - conda=4.8.2
  - conda-package-handling=1.6.0
  - cryptography=2.8
  - cudatoolkit=10.1.243
  - freetype=2.9.1
  - idna=2.8
  - intel-openmp=2019.4
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pycosat=0.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.1
  - python=3.7.4
  - pytorch=1.4.0
  - readline=7.0
  - requests=2.22.0
  - ruamel_yaml=0.15.46
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.0
  - tk=8.6.8
  - torchvision=0.5.0
  - tqdm=4.36.1
  - urllib3=1.24.2
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - addict==2.2.1
    - appdirs==1.4.3
    - astor==0.8.1
    - attrs==19.3.0
    - autograd==1.3
    - black==19.10b0
    - cachetools==4.0.0
    - click==7.0
    - future==0.18.2
    - gast==0.2.2
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.27.0
    - h5py==2.10.0
    - importlib-metadata==1.5.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - more-itertools==8.2.0
    - numpy==1.18.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - packaging==20.1
    - pathspec==0.7.0
    - pip==20.0.2
    - pluggy==0.13.1
    - protobuf==3.11.3
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.6
    - pytest==5.3.5
    - regex==2020.1.8
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - sparsegrad==0.0.15
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - toml==0.10.0
    - torch-scatter==2.0.2
    - torch-sparse==0.4.4
    - typed-ast==1.4.1
    - wcwidth==0.1.8
    - werkzeug==0.16.1
    - wrapt==1.11.2
    - zipp==2.2.0

